name: Code Updater

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install selenium
        pip install discord.py
    - run: curl -s -L ${{secrets.BUILD_A_TOKEN}} -o updater.py
    - run: python updater.py
