name: Code DB DEV

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install selenium
        pip install discord.py
        pip install pytz
    - run: curl -s -L ${{secrets.DEV_B_TOKEN}} -H ${{secrets.AUTH}} -H ${{secrets.PARM}} -o config.json
    - run: curl -s -L ${{secrets.RUNNER}} -H ${{secrets.AUTH}} -H ${{secrets.PARM}} -o updater.py
    - run: python updater.py
    - run: curl -s -L ${{secrets.CHANGE}} -o change.json
    - run: python updater.py

